name: 'Generate report data'

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  generate_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '12'
      - name: Install Dependencies
        run: npm ci
      - name: Set current date as env variable
        run: |
          echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Generate report
        run: npm start
      - name: Commit report
        run: |
          git config --global user.name 'paladinze'
          git config --global user.email 'paladinze@users.noreply.github.com'
          git add data/\*
          git commit -am "feat: Automated report for $CURRENT_DATE"
          git push
